// Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// Product
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

// Cart
export const SET_CART = 'SET_CART'
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART'

// Contact
export const SEND_EMAIL = 'SEND_EMAIL'

// Error
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
